version: '3'
services:
  db:
    image:  postgres:14 # Image with postgresql
    expose:
      - 5432
    # Expose local port to host for dev
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER:  root # Change for yours
      POSTGRES_PASSWORD:  root # Change for yours
      POSTGRES_DB: itc_system # Change for yours

  api:
    build: ${BACKEND_SOURCE}
    command: python3 /api/app/main.py
    volumes:
      - .:/usr/src/itc_system
    ports: # Expose docker 8080 port (rest api) to host machine
      - 8080:8080
    depends_on:
      - db
  
  frontend:
    build: ${FRONTEND_SOURCE}
    tty: true
    stdin_open: true
      #command: "npx pm2 serve build --force --spa --port 3000"
      #command: "tail -f /dev/null"
    command: "npx pm2 --no-daemon serve build --port 3000 --spa" #"npx pm2 serve build --force --spa --port 9090"
      #command: "npx pm2 serve build --force --spa --port 9090 & tail -f /dev/null"
    depends_on: 
      - api
    ports: # Expose docker 3000 port (frontend) to host machine
      - 3000:3000

volumes:
  postgres_data:
