version: '3'
services:
  db:
    image:  postgres:14
    expose:
      - 5432
    # Expose local port to host for dev
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER:  root
      POSTGRES_PASSWORD:  root
      POSTGRES_DB: itc_system

  api:
    build: ${BACKEND_SOURCE}
    command: python3 /api/app/main.py
    volumes:
      - .:/usr/src/itc_system
    ports:
      - 8080:8080
    depends_on:
      - db
  frontend:
    build: ${FRONTEND_SOURCE}
    command: npx serve build
    depends_on:
      - api
    ports:
      - 3000:3000

volumes:
  postgres_data:



