version: '2.1'
services:
  db:
    image:  postgres:14 # Image with postgresql
    # Expose local port to host for dev
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER:  root # Change for yours
      POSTGRES_PASSWORD:  root # Change for yours
      POSTGRES_DB: itc_system # Change for yours
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 1s
      timeout: 5s
      retries: 30

  api:
    build: ${BACKEND_SOURCE}
    command: python3 /api/app/main.py
    volumes:
      - .:/usr/src/itc_system
      - ../Backend/app/static/:/api/app/static
    ports: # Expose docker 8080 port (rest api) to host machine
      - "8080:8080"
    environment:
      ITC_DATABASE_URL: "postgresql://root:root@db:5432/itc_system"
      ITC_SERV_PORT: 8080
      ITC_SERV_HOST: "0.0.0.0"
      ITC_SECRET_KEY: "ha58:yadyfysdydhcwhifbfsdu723772s"
      ITC_ACCESS_TOKEN_EXPIRE_MINUTES: 1440
      ITC_USERS_STORAGE: "/api/app/static/users_data/uploads/"
      ITC_API_VER: "0.0.3"
      ITC_SETUP_MODE: 1
      ITC_CHECKER_SERVICE: "http://172.17.0.1:7777"
      ITC_ROOT_PATH: "/api"

    depends_on:
      db:
        condition: service_healthy
  
  frontend:
    build: ${FRONTEND_SOURCE}
    command: npx pm2 --no-daemon serve build --port 3000 --spa
    depends_on: 
      - api
    ports: # Expose docker 3000 port (frontend) to host machine
      - "3000:3000"

  nginx:
    depends_on:
      - api
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

volumes:
  postgres_data:
