version: '1'
services:
  db:
    image:  postgres:14 # Image with postgresql
    # Expose local port to host for dev
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER:  root # Change for yours
      POSTGRES_PASSWORD:  root # Change for yours
      POSTGRES_DB: itc_system # Change for yours

  api:
    build: ${BACKEND_SOURCE}
    command: python3 /api/app/main.py
    volumes:
      - .:/usr/src/itc_system
    ports: # Expose docker 8080 port (rest api) to host machine
      - 8080:8080
    depends_on:
      - db
  
  frontend:
    build: ${FRONTEND_SOURCE}
    command: npx pm2 --no-daemon serve build --port 3000 --spa
    depends_on: 
      - api
    ports: # Expose docker 3000 port (frontend) to host machine
      - 3000:3000

  nginx:
    depends_on:
      - api
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

volumes:
  postgres_data:
